export const menuItems = [
  {
    id: 1,
    name: "Lahmacun",
    description: "A thin, crispy flatbread topped with seasoned minced meat, vegetables, and herbs.",
    price: 5.99,
    image: "/images/menu/lahmacun.jpeg",
    category: "Main Dishes",
    options: ["Spicy", "Regular"],
  },
  {
    id: 2,
    name: "Adana Kebab",
    description: "A long, hand-minced meat kebab mounted on a wide iron skewer and grilled over charcoal.",
    price: 12.99,
    image: "/images/menu/adana-kebab.jpeg",
    category: "Main Dishes",
    options: ["Spicy", "Regular"],
  },
  {
    id: 3,
    name: "Urfa Kebab",
    description: "Similar to Adana Kebab but less spicy, made with ground lamb and spices.",
    price: 12.99,
    image: "/images/menu/urfa-kebab.jpeg",
    category: "Main Dishes",
    options: ["Spicy", "Regular"],
  },
  {
    id: 4,
    name: "Iskender Kebab",
    description: "Slices of döner kebab served on a bed of pita bread, topped with tomato sauce and melted butter.",
    price: 14.99,
    image: "/images/menu/iskender-kebab.jpeg",
    category: "Main Dishes",
  },
  {
    id: 5,
    name: "Döner Kebab",
    description: "Meat cooked on a vertical rotisserie, typically lamb, chicken, or beef.",
    price: 9.99,
    image: "/images/menu/doner-kebab.jpeg",
    category: "Main Dishes",
    options: ["Chicken", "Beef", "Lamb"],
  },
  {
    id: 6,
    name: "Pide",
    description: "Turkish pizza, a flatbread topped with various ingredients such as cheese, meat, and vegetables.",
    price: 8.99,
    image: "/images/menu/pide.jpeg",
    category: "Main Dishes",
    options: ["Cheese", "Meat", "Vegetarian"],
  },
  {
    id: 7,
    name: "Baklava",
    description:
      "A rich, sweet pastry made of layers of filo filled with chopped nuts and sweetened with syrup or honey.",
    price: 6.99,
    image: "/images/menu/baklava.jpeg",
    category: "Desserts",
  },
  {
    id: 8,
    name: "Künefe",
    description: "A traditional Middle Eastern dessert made with cheese pastry soaked in sweet, sugar-based syrup.",
    price: 7.99,
    image: "/images/menu/kunefe.jpeg",
    category: "Desserts",
  },
  {
    id: 9,
    name: "Sütlaç",
    description: "Turkish rice pudding, a creamy dessert made with milk, rice, and sugar.",
    price: 5.99,
    image: "/images/menu/sutlac.jpeg",
    category: "Desserts",
  },
  {
    id: 10,
    name: "Ayran",
    description: "A refreshing yogurt-based drink, popular in Turkey.",
    price: 2.99,
    image: "/images/menu/ayran-drink-new.jpeg",
    category: "Drinks",
  },
  {
    id: 11,
    name: "Turkish Coffee",
    description: "A strong, unfiltered coffee prepared using very finely ground coffee beans.",
    price: 3.99,
    image: "/images/menu/turkish-coffee.jpeg",
    category: "Drinks",
  },
  {
    id: 12,
    name: "Turkish Tea",
    description: "A type of black tea which is popular in Turkey and the Turkish diaspora.",
    price: 2.49,
    image: "/images/menu/turkish-tea.jpeg",
    category: "Drinks",
  },
  {
    id: 13,
    name: "Pita Bread",
    description: "Soft, slightly leavened flatbread baked from wheat flour.",
    price: 1.99,
    image: "/images/menu/pita-bread-new.jpeg",
    category: "Sides",
  },
  {
    id: 14,
    name: "Hummus",
    description: "A dip made from cooked, mashed chickpeas blended with tahini, lemon juice, and garlic.",
    price: 4.99,
    image: "/images/menu/hummus.jpeg",
    category: "Sides",
  },
]
